# -*- coding: utf-8 -*-
"""Analise_temperaturas_piracicaba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u5-ydsJcfi7XEtoLT4u-xpXyXRzIDMXs
"""

import numpy as np
import matplotlib.pyplot as plt
from csv import reader
from matplotlib import style
style.use('ggplot')

"""Temperatura máxima da cidade de Piracicaba no ano de 1999"""

with open('temperaturas.csv.pub') as file:
    parsed = reader(file)
    data_1999=list(filter(lambda v : v[0] == '1999.0', parsed))
    
    max_temp=[float(v[3]) for v in data_1999 if v[3]]
    med_temp=[float(v[4]) for v in data_1999 if v[4]]
    min_temp=[float(v[5]) for v in data_1999 if v[5]]
    
    plt.plot(max_temp, 'b:', label='Temperatua máxima')
    plt.plot(med_temp, 'm', label='Temperatua média')
    plt.plot(min_temp,'k', label='Temperatua mínima')
    plt.grid(True, lw=1,ls='--')
    plt.legend()
    plt.title('Faixas de Temperatura da cidade de Piracicaba-SP')
    plt.ylabel('Temperaturas')
    plt.xlabel('Dias do ano')
    plt.show()

